name: Run Test on Push for Java and Kotlin

on: push

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 11
    - name: Chang Mod
      working-directory: ./JavaKotlin
      run: chmod 755 gradlew    
    - name: run-test
      working-directory: ./JavaKotlin
      run: ./gradlew test
