name: Run Test on Push for Java and Kotlin

on: push

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-java@master
      with:
        java-version: 11
    - name: Chang Mod
      run: chmod 755 gradlew    
    - name: run-test
      working-directory: ./JavaKotlin
      run: ./gradlew test
