name: Run Test on Push for Java and Kotlin

on: push

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-java@master
      with:
        java-version: 11
    - name: Chang Mod
      run: chmod 755 gradlew    
    - name: run-test
      working-directory: ./JavaKotlin
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: test
